UTILITIES_MATERIAL_QUOTE = "utilities.material.quote"
UTILITIES_JOB_QUOTE = "utilities.job.quote"

SUPPLIER = "group_ship_supplier"
TECHNICAL_EXPERT = "group_ship_technical_expert"


PENDING = "PENDING"
APPROVED = "APPROVED"
REJECTED = "REJECTED"

APPROVAL_STATES = [
    (APPROVED, "Approved"),
    (PENDING, "Pending"),
    (REJECTED, "Rejected"),
]

MATERIAL = "MATERIAL"
SPARE_PART = "SPARE_PART"
PAINT = "PAINT"

MATERIAL_TYPE = [
    (MATERIAL, "Material"),
    (SPARE_PART, "Spare part"),
    (PAINT, "Paint"),
]

MACHINERY = "MACHINERY"
BOONG = "BOONG"

DEPARTMENT_IN_CHARGE = [
    (MACHINERY, "Machinery"),
    (BOONG, "Boong"),
]

UNAPPROVED = "UNAPPROVED"
TODO = "TODO"
WORKING = "WORKING"
COMPLETED = "COMPLETED"
CONFIRMED = "CONFIRMED"


JOB_STATES = [
    (UNAPPROVED, "Unapproved"),
    (TODO, "Todo"),
    (WORKING, "Working"),
    (COMPLETED, "Completed"),
    (CONFIRMED, "Confirmed"),
]

APPROVAL_FLOW_TYPE_SURVEY = "survey-approval-flow"
APPROVAL_FLOW_TYPE_JOB_QUOTE = "job-quote-approval-flow"
APPROVAL_FLOW_TYPE_MATERIAL_QUOTE = "material-quote-approval-flow"
APPROVAL_FLOW_TYPE_EXPECTED_COST_REPORT = "expected-cost-report-approval-flow"
APPROVAL_FLOW_TYPE_SCOPE_REPORT = "maintenance-scope-report-approval-flow"
APPROVAL_FLOW_TYPE_CONTRACT = "contract-flow"
APPROVAL_FLOW_TYPE_PROPOSED_LIQUIDATION = "proposed-liquidation-flow"
APPROVAL_FLOW_TYPE_COST_SETTLEMENT_REPORT = "cost-settlement-report-flow"
APPROVAL_FLOW_TYPE_INSPECTION_PLAN = "inspection-plan-flow"
APPROVAL_FLOW_TYPE_TECHNICAL_INCIDENT = "technical-incident-flow"
APPROVAL_FLOW_TYPE_EXPIRED_MATERIAL_ENTITY_REPLACEMENT_PROPOSAL = (
    "expired-material-entity-replacement-proposal"
)


APPROVAL_FLOW_TYPES = [
    (APPROVAL_FLOW_TYPE_SURVEY, "Survey approval flow"),
    (APPROVAL_FLOW_TYPE_JOB_QUOTE, "Job quote approval flow"),
    (APPROVAL_FLOW_TYPE_MATERIAL_QUOTE, "Material/Paint quote approval flow"),
    (APPROVAL_FLOW_TYPE_EXPECTED_COST_REPORT, "Expected cost report approval flow"),
    (APPROVAL_FLOW_TYPE_SCOPE_REPORT, "Maintenance scope report approval flow"),
    (APPROVAL_FLOW_TYPE_CONTRACT, "Contract approval flow"),
    (APPROVAL_FLOW_TYPE_PROPOSED_LIQUIDATION, "Proposed liquidation approval flow"),
    (APPROVAL_FLOW_TYPE_COST_SETTLEMENT_REPORT, "Cost settlement report approval flow"),
    (APPROVAL_FLOW_TYPE_INSPECTION_PLAN, "Inspection plan approval flow"),
    (APPROVAL_FLOW_TYPE_TECHNICAL_INCIDENT, "Technical incident approval flow"),
    (
        APPROVAL_FLOW_TYPE_EXPIRED_MATERIAL_ENTITY_REPLACEMENT_PROPOSAL,
        "Expired material entity replacement proposal approval flow",
    ),
]

USER_FOR_NOTIFICATION = "USER_FOR_NOTIFICATION"
EXPECT_START_DATE = "EXPECT_START_DATE"
HTML_VALUE = "HTML_VALUE"

FIELD = "FIELD"
RELATION_FIELDS = "RELATION_FIELDS"
NOTIFICATION_FOR_USER = "NOTIFICATION_FOR_USER"
APPROVAL_REMINDER_NOTIFICATION = "APPROVAL_REMINDER_NOTIFICATION"
DEFAULT_TYPES = [
    (RELATION_FIELDS, "Relation fields"),
    (FIELD, "Field"),
    (NOTIFICATION_FOR_USER, "Notification for users"),
    (APPROVAL_REMINDER_NOTIFICATION, "Approval reminder notification"),
]

NOTIFICATION_FOR_APPROVED = "NOTIFICATION_FOR_APPROVED"
PREPARE_FOR_INSPECTION_PLAN = "PREPARE_FOR_INSPECTION_PLAN"
NEED_REAL_DATE_FOR_INSPECTION_PLAN = "NEED_REAL_DATE_FOR_INSPECTION_PLAN"
FILL_IN_START_DATE_IN_DOCKING_PLAN = "FILL_IN_START_DATE_IN_DOCKING_PLAN"
CHANGING_INSPECTION_DATE = "CHANGING_INSPECTION_DATE"
CONFIRM_INSPECTION_DATE = "CONFIRM_INSPECTION_DATE"
NOTI_DOCKING_PLAN_BEFORE_3_MONTHS = "NOTI_DOCKING_PLAN_BEFORE_3_MONTHS"
NOTI_DOCKING_PLAN_BEFORE_6_MONTHS = "NOTI_DOCKING_PLAN_BEFORE_6_MONTHS"

NOTIFICATION_TYPES = [
    (NOTIFICATION_FOR_APPROVED, NOTIFICATION_FOR_APPROVED),
    (PREPARE_FOR_INSPECTION_PLAN, PREPARE_FOR_INSPECTION_PLAN),
    (NEED_REAL_DATE_FOR_INSPECTION_PLAN, NEED_REAL_DATE_FOR_INSPECTION_PLAN),
    (FILL_IN_START_DATE_IN_DOCKING_PLAN, FILL_IN_START_DATE_IN_DOCKING_PLAN),
    (CHANGING_INSPECTION_DATE, CHANGING_INSPECTION_DATE),
    (NOTI_DOCKING_PLAN_BEFORE_3_MONTHS, NOTI_DOCKING_PLAN_BEFORE_3_MONTHS),
    (NOTI_DOCKING_PLAN_BEFORE_6_MONTHS, NOTI_DOCKING_PLAN_BEFORE_6_MONTHS),
]

STRING = "STRING"
INTEGER = "INTEGER"
FLOAT = "FLOAT"
DATE = "DATE"
HTML = "HTML"
USERS = "USERS"
GROUPS = "GROUPS"
RELATION = "RELATION"

VALUE_TYPES = [
    (STRING, "String"),
    (INTEGER, "Integer"),
    (FLOAT, "Float"),
    (DATE, "Date"),
    (HTML, "Html"),
    (USERS, "Users"),
    (GROUPS, "Groups"),
    (RELATION, "Relation"),
]

PAYMENT_STATUS = [
    (PENDING, "Pending"),
    (COMPLETED, "Completed"),
]

NORMAL = "NORMAL"
ARISE = "ARISE"

ARISE_SELECTION = [
    (NORMAL, "Normal"),
    (ARISE, "Arise"),
]

MINUTES = "minutes"
HOURS = "hours"
DAYS = "days"

INTERVAL_TYPE = [
    (MINUTES, "Minutes"),
    (HOURS, "Hours"),
    (DAYS, "Days"),
]

HTML_CONTRACT_UNRENDERED_CONTENT = "HTML_CONTRACT_UNRENDERED_CONTENT"
RELATION_FUEL_EXTERNAL_FUEL_CHECKS = "RELATION_FUEL_EXTERNAL_FUEL_CHECKS"
RELATION_FUEL_INTERNAL_FUEL_CHECKS = "RELATION_FUEL_INTERNAL_FUEL_CHECKS"
DATE_DOCKING_PLAN_EXPECTED_DATE = "DATE_DOCKING_PLAN_EXPECTED_DATE"
HTML_HANDBOOK_CONTENT = "HTML_HANDBOOK_CONTENT"
HTML_TECHNICAL_INCIDENT_CONTENT = "HTML_TECHNICAL_INCIDENT_CONTENT"
HTML_TECHNICAL_INCIDENT_MARINE_PROTEST_CONTENT = (
    "HTML_TECHNICAL_INCIDENT_MARINE_PROTEST_CONTENT"
)
INTEGER_FUEL_CONSUMPTION_CURRENT_FO = "INTEGER_FUEL_CONSUMPTION_CURRENT_FO"
INTEGER_FUEL_CONSUMPTION_CURRENT_DO = "INTEGER_FUEL_CONSUMPTION_CURRENT_DO"
HTML_FUEL_EXTERNAL_BUNKERING_SAFETY_CHECKLIST = (
    "HTML_FUEL_EXTERNAL_BUNKERING_SAFETY_CHECKLIST"
)
HTML_FUEL_INTERNAL_BUNKERING_SAFETY_CHECKLIST = (
    "HTML_FUEL_INTERNAL_BUNKERING_SAFETY_CHECKLIST"
)
INTEGER_INSPECTION_PLAN_GENERAL_PRENOTI_DAYS = (
    "INTEGER_INSPECTION_PLAN_GENERAL_PRENOTI_DAYS"
)
INTEGER_INSPECTION_PLAN_SPECIALLIST_PRENOTI_DAYS = (
    "INTEGER_INSPECTION_PLAN_SPECIALLIST_PRENOTI_DAYS"
)
INTEGER_JOB_QUOTE_DEADLINE_DAY_COUNT = "INTEGER_JOB_QUOTE_DEADLINE_DAY_COUNT"
INTEGER_JOB_QUOTE_DAY_COUNT_VALID_FOT_EDITING_IMPLEMENT_DATE = (
    "INTEGER_JOB_QUOTE_DAY_COUNT_VALID_FOT_EDITING_IMPLEMENT_DATE"
)
INTEGER_MAINTENANCE_SCOPE_REPORT_DEADLINE_DAY_COUNT = (
    "INTEGER_MAINTENANCE_SCOPE_REPORT_DEADLINE_DAY_COUNT"
)
INTEGER_MATERIAL_PAINT_QUOTES_REQUEST_DEADLINE_DAY_COUNT = (
    "INTEGER_MATERIAL_PAINT_QUOTES_REQUEST_DEADLINE_DAY_COUNT"
)
HTML_EXPORT_REPORT_RENDERED_MEDICINE_CONTENT = (
    "HTML_EXPORT_REPORT_RENDERED_MEDICINE_CONTENT"
)
USERS_DOCKING_PLAN_FILL_IN_START_DATE = "USERS_DOCKING_PLAN_FILL_IN_START_DATE"
USERS_DOCKING_PLAN_NOTI_BEFORE_3_MONTHS = "USERS_DOCKING_PLAN_NOTI_BEFORE_3_MONTHS"
USERS_DOCKING_PLAN_NOTI_BEFORE_6_MONTHS = "USERS_DOCKING_PLAN_NOTI_BEFORE_6_MONTHS"
USERS_INSPECTION_EVENT_CONFIRM_INSPECTION_DATE = (
    "USERS_INSPECTION_EVENT_CONFIRM_INSPECTION_DATE"
)
USERS_INSPECTION_PLAN_NEED_PREPARE = "USERS_INSPECTION_PLAN_NEED_PREPARE"
USERS_INSPECTION_PLAN_NEED_REAL_DATE = "USERS_INSPECTION_PLAN_NEED_REAL_DATE"
USERS_APPROVAL_STATUS_NOTIFICATION_FOR_APPROVED = (
    "USERS_APPROVAL_STATUS_NOTIFICATION_FOR_APPROVED"
)
INTEGER_APPROVAL_STATUS_INTERVAL_NUMBER_TIME_FOR_APPROVER = (
    "INTEGER_APPROVAL_STATUS_INTERVAL_NUMBER_TIME_FOR_APPROVER"
)
STRING_APPROVAL_STATUS_INTERVAL_TYPE_TIME_FOR_APPROVER = (
    "STRING_APPROVAL_STATUS_INTERVAL_TYPE_TIME_FOR_APPROVER"
)
USERS_INSPECTION_EVENT_CHANGING_INSPECTION_DATE = (
    "USERS_INSPECTION_EVENT_CHANGING_INSPECTION_DATE"
)
INTEGER_FUEL_DAY_OF_THE_MONTH = "INTEGER_FUEL_DAY_OF_THE_MONTH"
GROUPS_SHIP_JOB_QUOTE_CHANGING_CONFIRM_JOB_STATE = (
    "GROUPS_SHIP_JOB_QUOTE_CHANGING_CONFIRM_JOB_STATE"
)


DEFAULT_VALUE_VARIABLE_NAMES = [
    (
        STRING_APPROVAL_STATUS_INTERVAL_TYPE_TIME_FOR_APPROVER,
        STRING_APPROVAL_STATUS_INTERVAL_TYPE_TIME_FOR_APPROVER,
    ),
    (INTEGER_FUEL_CONSUMPTION_CURRENT_FO, INTEGER_FUEL_CONSUMPTION_CURRENT_FO),
    (INTEGER_FUEL_CONSUMPTION_CURRENT_DO, INTEGER_FUEL_CONSUMPTION_CURRENT_DO),
    (
        INTEGER_INSPECTION_PLAN_GENERAL_PRENOTI_DAYS,
        INTEGER_INSPECTION_PLAN_GENERAL_PRENOTI_DAYS,
    ),
    (
        INTEGER_INSPECTION_PLAN_SPECIALLIST_PRENOTI_DAYS,
        INTEGER_INSPECTION_PLAN_SPECIALLIST_PRENOTI_DAYS,
    ),
    (INTEGER_JOB_QUOTE_DEADLINE_DAY_COUNT, INTEGER_JOB_QUOTE_DEADLINE_DAY_COUNT),
    (
        INTEGER_JOB_QUOTE_DAY_COUNT_VALID_FOT_EDITING_IMPLEMENT_DATE,
        INTEGER_JOB_QUOTE_DAY_COUNT_VALID_FOT_EDITING_IMPLEMENT_DATE,
    ),
    (
        INTEGER_MAINTENANCE_SCOPE_REPORT_DEADLINE_DAY_COUNT,
        INTEGER_MAINTENANCE_SCOPE_REPORT_DEADLINE_DAY_COUNT,
    ),
    (
        INTEGER_MATERIAL_PAINT_QUOTES_REQUEST_DEADLINE_DAY_COUNT,
        INTEGER_MATERIAL_PAINT_QUOTES_REQUEST_DEADLINE_DAY_COUNT,
    ),
    (
        INTEGER_APPROVAL_STATUS_INTERVAL_NUMBER_TIME_FOR_APPROVER,
        INTEGER_APPROVAL_STATUS_INTERVAL_NUMBER_TIME_FOR_APPROVER,
    ),
    (
        INTEGER_FUEL_DAY_OF_THE_MONTH,
        INTEGER_FUEL_DAY_OF_THE_MONTH,
    ),
    (DATE_DOCKING_PLAN_EXPECTED_DATE, DATE_DOCKING_PLAN_EXPECTED_DATE),
    (HTML_CONTRACT_UNRENDERED_CONTENT, HTML_CONTRACT_UNRENDERED_CONTENT),
    (
        HTML_FUEL_EXTERNAL_BUNKERING_SAFETY_CHECKLIST,
        HTML_FUEL_EXTERNAL_BUNKERING_SAFETY_CHECKLIST,
    ),
    (HTML_HANDBOOK_CONTENT, HTML_HANDBOOK_CONTENT),
    (
        HTML_TECHNICAL_INCIDENT_MARINE_PROTEST_CONTENT,
        HTML_TECHNICAL_INCIDENT_MARINE_PROTEST_CONTENT,
    ),
    (
        HTML_EXPORT_REPORT_RENDERED_MEDICINE_CONTENT,
        HTML_EXPORT_REPORT_RENDERED_MEDICINE_CONTENT,
    ),
    (
        HTML_FUEL_INTERNAL_BUNKERING_SAFETY_CHECKLIST,
        HTML_FUEL_INTERNAL_BUNKERING_SAFETY_CHECKLIST,
    ),
    (USERS_DOCKING_PLAN_FILL_IN_START_DATE, USERS_DOCKING_PLAN_FILL_IN_START_DATE),
    (USERS_DOCKING_PLAN_NOTI_BEFORE_3_MONTHS, USERS_DOCKING_PLAN_NOTI_BEFORE_3_MONTHS),
    (USERS_DOCKING_PLAN_NOTI_BEFORE_6_MONTHS, USERS_DOCKING_PLAN_NOTI_BEFORE_6_MONTHS),
    (
        USERS_INSPECTION_EVENT_CONFIRM_INSPECTION_DATE,
        USERS_INSPECTION_EVENT_CONFIRM_INSPECTION_DATE,
    ),
    (USERS_INSPECTION_PLAN_NEED_PREPARE, USERS_INSPECTION_PLAN_NEED_PREPARE),
    (USERS_INSPECTION_PLAN_NEED_REAL_DATE, USERS_INSPECTION_PLAN_NEED_REAL_DATE),
    (
        USERS_APPROVAL_STATUS_NOTIFICATION_FOR_APPROVED,
        USERS_APPROVAL_STATUS_NOTIFICATION_FOR_APPROVED,
    ),
    (
        USERS_INSPECTION_EVENT_CHANGING_INSPECTION_DATE,
        USERS_INSPECTION_EVENT_CHANGING_INSPECTION_DATE,
    ),
    (
        GROUPS_SHIP_JOB_QUOTE_CHANGING_CONFIRM_JOB_STATE,
        GROUPS_SHIP_JOB_QUOTE_CHANGING_CONFIRM_JOB_STATE,
    ),
    (
        RELATION_FUEL_INTERNAL_FUEL_CHECKS,
        RELATION_FUEL_INTERNAL_FUEL_CHECKS,
    ),
    (
        RELATION_FUEL_EXTERNAL_FUEL_CHECKS,
        RELATION_FUEL_EXTERNAL_FUEL_CHECKS,
    ),
]

SECOND_TIME_APPROVAL_OPTION_VALUE = "SECOND_TIME_APPROVAL_OPTION_VALUE"
