from . import technical_incident
from . import technical_incident_job
from . import technical_incident_insurance
from . import safety_management_handbook
from . import handbook_section
from . import ert_role_task_meta
from . import ert_role_meta
from . import incidence_type_meta
from . import serious_accident
from . import ert_task
from . import serious_accident_task
from . import editing_request_for_handbook
from . import changed_content_of_handbook
from .many_relations import ship_material_assignment_legis_technical_incident_job_rel
from .many_relations import ship_maintenance_scope_report_legis_technical_incident_rel
