{
    "name": "Ship Management System",
    "author": "Techno THT Gmbh",
    "website": "www.techno-tht.tech",
    "summary": "Application for ship management",
    "depends": [
        "report_xlsx",
        "website",
        "portal",
        "mail",
        "web_window_title",
        "utilities",
    ],
    "data": [
        "security/role.xml",
        "security/rule.xml",
        "security/ir.model.access.csv",
        "data/channels.xml",
        "data/sequence.xml",
        "data/supplier_quote_email_cron.xml",
        "data/material_rfq_mail_templates.xml",
        "data/paint_rfq_mail_templates.xml",
        "data/job_rfq_mail_templates.xml",
        "data/fuel_rfq_mail_templates.xml",
        "data/paint_cron.xml",
        "data/refresh_supplier_portal_access_token_cron.xml",
        "data/access_supplier_portal_mail_templates.xml",
        "data/supplier_quote_change_portal_mail_template.xml",
        "data/material_paint_quotes_request_cron.xml",
        "data/expired_material_entity_replacement_proposal_cron.xml",
        "data/inspection_plan_cron.xml",
        "views/menu.xml",
        "views/supplier.xml",
        "views/material.xml",
        "views/material_group.xml",
        "views/material_entity.xml",
        "views/material_usage_type.xml",
        "views/material_paint_quotes_request.xml",
        "views/material_quote.xml",
        "views/maintenance_scope_report.xml",
        "views/paint_quote.xml",
        "views/job_quote.xml",
        "views/material_supplier_quote.xml",
        "views/paint_supplier_quote.xml",
        "views/job_supplier_quote.xml",
        "views/paint.xml",
        "views/paint_type.xml",
        "views/paint_history.xml",
        "views/equipment.xml",
        "views/maintenance_scope.xml",
        "views/job.xml",
        "views/job_material_requirement.xml",
        "views/job_paint_requirement.xml",
        "views/material_assignment.xml",
        "views/area_of_paint_job.xml",
        "views/portal_material_rfq_templates.xml",
        "views/portal_job_rfq_templates.xml",
        "views/portal_paint_rfq_templates.xml",
        "views/portal_rfq_templates.xml",
        "views/classify.xml",
        "views/material_consumption_report.xml",
        "views/fuel_consumption_report.xml",
        "views/job_quote_report.xml",
        "views/fuel.xml",
        "views/unit.xml",
        "views/utilization_time.xml",
        "views/port.xml",
        "views/fuel_quote.xml",
        "views/fuel_quotes_request.xml",
        "views/fuel_supplier_quote.xml",
        "views/replacement_diary.xml",
        "views/proposed_liquidation.xml",
        "views/liquidation_minute.xml",
        "views/supplier_quote_portal_change_notification.xml",
        "views/expired_material_entity_replacement_proposal.xml",
        "views/fuel_internal_receiving.xml",
        "views/fuel_external_receiving.xml",
        "views/sounding.xml",
        "views/lashing_material_fix_stats.xml",
        "views/inspection_plan.xml",
        "views/ship_management_inspection_scope.xml",
        "views/technical_inspection_scope.xml",
        "views/ship_management_inspection_task.xml",
        "views/technical_inspection_task.xml",
        "views/ship_management_inspection_scope_metadata.xml",
        "views/technical_inspection_scope_metadata.xml",
        "views/ship_management_inspection_task_metadata.xml",
        "views/technical_inspection_task_metadata.xml",
        "views/inspection_image.xml",
        "wizard/create_utilization_time_wiz.xml",
        "wizard/export_report.xml",
        "reports/report.xml",
        "reports/medicine.xml",
        "reports/ship_e_bunkering_safety_checklist_pdf.xml",
    ],
    "application": True,
    "post_init_hook": "post_init_hook",
    "assets": {
        "web.assets_common": [
            "ship_management/static/src/xml/express_confirm_material_entity_delivery.xml",
        ],
        "web.assets_backend": [
            "ship_management/static/src/css/odoo.css",
            "ship_management/static/src/css/my_css.css",
            "ship_management/static/src/css/kanban_styles.css",
            "ship_management/static/src/lib/qrcode.min.js",
            "ship_management/static/src/lib/html5-qrcode.min.js",
            "ship_management/static/src/js/express_confirm_material_entity_delivery.js",
            "ship_management/static/src/js/print_qr.js",
        ],
    },
}
