name: Build, push Docker Image and deploy to Dev
on:
  push:
    branches:
      - main
      - 'dev-*'
      - 'feature/dev-*'
      - 'hotfix/dev-*'
      - 'fix/dev-*'
      - 'bugfix/dev-*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Docker tag
        id: set_tag
        run: echo "::set-output name=tag::${{ github.ref }}"

      - name: Login Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: ./
          file: ./Dockerfile.amd64
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: thttechno/vsico:quan-ly-tau-thuy-dev

      - name: Set up Kubernetes context
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.DEV_KUBECONFIG }}
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
          
      - name: Create namespace and ignore error if it already exists
        run: kubectl create namespace quan-ly-tau-dev
        continue-on-error: true

      - name: Create docker-registry secret and ignore error if it already exists
        run: kubectl create --namespace quan-ly-tau-dev secret docker-registry docker-hub-registry --docker-username=${{ secrets.DOCKER_REGISTRY_USERNAME }} --docker-password=${{ secrets.DOCKER_REGISTRY_PASSWORD }}
        continue-on-error: true

      - name: Uninstall helm chart
        run: helm uninstall quan-ly-tau-dev --namespace quan-ly-tau-dev
        continue-on-error: true
      
      - name: Upgrade/Install helm chart
        run: |
          helm upgrade --install --wait --wait-for-jobs --timeout 30m \
            --set image.tag=quan-ly-tau-thuy-dev \
            --set image.pullPolicy=Always \
            --set service.type=LoadBalancer \
            --set service.port=8069 \
            --set ingress.enabled=false \
            --set qltOdooPV.name=quan-ly-tau-data-pv-dev-volume \
            --set qltOdooPV.hostPath=/home/qlt-data-dev \
            --set postgresql.primary.service.ports.postgresql=53554 \
            --set postgresql.primary.pgHbaConfiguration=null \
            quan-ly-tau-dev ./helmchart --namespace quan-ly-tau-dev
