{
    "name": "Ship safety legislation",
    "author": "Techno THT Gmbh",
    "website": "www.techno-tht.tech",
    "summary": "Ship safety legislation",
    "depends": ["ship_management"],
    "data": [
        "security/rule.xml",
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "views/menu.xml",
        "views/technical_incident.xml",
        "views/technical_incident_job.xml",
        "views/technical_incident_insurance.xml",
        "views/safety_management_handbook.xml",
        "views/handbook_section.xml",
        "views/ert_role_task_meta.xml",
        "views/ert_role_meta.xml",
        "views/incidence_type_meta.xml",
        "views/serious_accident.xml",
        "views/ert_task.xml",
        "views/serious_accident_task.xml",
        "views/editing_request_for_handbook.xml",
        "views/changed_content_of_handbook.xml",
        "reports/report.xml",
        "reports/technical_incident_pdf.xml",
        "reports/marine_protest_pdf.xml",
    ],
    "application": True,
    "assets": {
        "web.assets_backend": [
            "safety_legislation/static/css/my_css.css",
            "safety_legislation/static/css/odoo.css",
        ],
    },
}
